print("Name:Catherine Dela Cruz")
print("Adress:Tanza, Boac, Marinduque")
print("Birthday:February 23 2003")
print("Course:BACHELOR OF SCIENCE IN INFORMATION Technology")
print("Year:2nd Year")
print("BSI/T 2C")
print("Animal Keeping")
print("Exploring the Internet")
print ("Playing Online Games")
print("Taking Photos with Nature")
print ("Traveling")